import { z } from "zod";
import {
  Home,
  Users,
  Shield,
  UserCheck,
  MapPin,
  Wallet,
  Activity,
  BarChart,
  AlertTriangle,
} from "lucide-react";

const enumForValidation = ["a"];
export const RegistrationSteps = [
  "Validating your details",
  "Sending Aadhaar OTP",
  "Verifying Aadhaar OTP",
  "Uploading docs securely",
  "Creating Custodial Wallet",
  "Minting NFT Tourist ID",
  "Finalizing trip data",
  "Completed!",
];
export const RegisterFormSchema = z
  .object({
    fullName: z.string().min(3, "full name is required"),
    DOB: z.date("Invalid Date Format"),
    idType: z.enum(["adhaarCard", "panCard"]),
    adhaarCardValue: z.number().optional(),
    panCardValue: z
      .object({
        panNo: z.string().optional(),
        dateOfBirth: z.string().optional(),
        name: z.string().optional(),
      })
      .optional(),
    phoneNumber: z.string().min(8, "Phone Number Is required"),
    email: z.email("Email is required"),

    emergencyContactOne: z.object({
      phoneNumber: z.string().min(8, "COntact Phone Nuber is Required"),
      name: z.string().min(3, "minimm three letter required"),
      relation: z.string().min(3, "minimm three letter required"),
    }),
    emergencyContactTwo: z
      .object({
        phoneNumber: z.string().optional(),
        name: z.string().optional(),
        relation: z.string().optional(),
      })
      .optional(),

    tripStart: z.date(),
    tripEnd: z.date("Invalid Date Format"),
    accomodation: z.string().optional(),
    tripPurpose: z.enum(["travel", "buisness", "other"]),
    tripDetails: z.string().optional(),
    tripState: z.string().min(2, "State is required"),
    tripCity: z.string("City is required"),
    healthInfo: z.string().optional(),
  })
  .superRefine((data, ctx) => {
    if (data.idType === "adhaarCard") {
      if (!data.adhaarCardValue) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Aadhaar Card number is required",
          path: ["adhaarCardValue"],
        });
      }
    }
    if (data.idType === "panCard") {
      if (!data.panCardValue?.panNo || data.panCardValue.panNo.length < 1) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "PAN number is required",
          path: ["panCardValue.panNo"],
        });
      }
      if (!data.panCardValue?.name || data.panCardValue.name.length < 1) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Name on PAN Card is required",
          path: ["panCardValue.name"],
        });
      }
      if (
        !data.panCardValue?.dateOfBirth ||
        data.panCardValue.dateOfBirth.length < 1
      ) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Date of Birth on PAN Card is required",
          path: ["panCardValue.dateOfBirth"],
        });
      }
    }
  });

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. Swaziland)",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export const indiaRegions = [
  { state: "Andhra Pradesh", state_iso2: "AP" },
  { state: "Arunachal Pradesh", state_iso2: "AR" },
  { state: "Assam", state_iso2: "AS" },
  { state: "Bihar", state_iso2: "BR" },
  { state: "Chhattisgarh", state_iso2: "CT" },
  { state: "Goa", state_iso2: "GA" },
  { state: "Gujarat", state_iso2: "GJ" },
  { state: "Haryana", state_iso2: "HR" },
  { state: "Himachal Pradesh", state_iso2: "HP" },
  { state: "Jharkhand", state_iso2: "JH" },
  { state: "Karnataka", state_iso2: "KA" },
  { state: "Kerala", state_iso2: "KL" },
  { state: "Madhya Pradesh", state_iso2: "MP" },
  { state: "Maharashtra", state_iso2: "MH" },
  { state: "Manipur", state_iso2: "MN" },
  { state: "Meghalaya", state_iso2: "ML" },
  { state: "Mizoram", state_iso2: "MZ" },
  { state: "Nagaland", state_iso2: "NL" },
  { state: "Odisha", state_iso2: "OR" },
  { state: "Punjab", state_iso2: "PB" },
  { state: "Rajasthan", state_iso2: "RJ" },
  { state: "Sikkim", state_iso2: "SK" },
  { state: "Tamil Nadu", state_iso2: "TN" },
  { state: "Telangana", state_iso2: "TS" },
  { state: "Tripura", state_iso2: "TR" },
  { state: "Uttar Pradesh", state_iso2: "UP" },
  { state: "Uttarakhand", state_iso2: "UK" },
  { state: "West Bengal", state_iso2: "WB" },
];

export const formSchema = z.object({
  email: z
    .string()
    .regex(/^[^\s@]+@[^\s@]+\.[^\s@]+$/, "Invalid email address format")
    .min(5)
    .max(50),
});

export const otpSchema = z.object({
  otpCode: z
    .string()
    .min(6, "minimum 6 digit is required")
    .max(6, "minimum six digit is required"),
});
export const menuItems = [
  { id: "dashboard", label: "Dashboard", icon: Home, path: "/dashboard" },
  {
    id: "manage",
    label: "Manage Tours",
    icon: MapPin,
    path: "/dashboard/manage",
  },
  {
    id: "register",
    label: "Register Tourist",
    icon: UserCheck,
    path: "/dashboard/register",
  },
  { id: "map", label: "Geo Map", icon: MapPin, path: "/dashboard/map" },
  {
    id: "analytics",
    label: "Analytics",
    icon: BarChart,
    path: "/dashboard/analytics",
  },
  {
    id: "incidents",
    label: "Incidents",
    icon: AlertTriangle,
    path: "/dashboard/incidents",
  },
  {
    id: "nftWallet",
    label: "NFT Wallet",
    icon: Wallet,
    path: "/dashboard/nft-wallet",
  },
  {
    id: "systemHealth",
    label: "System Health",
    icon: Activity,
    path: "/dashboard/system-health",
  },
];
