import type { Metadata } from "next";
import { TRPCProvider } from "@/trpc/client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function Provider({ children }: { children: React.ReactNode }) {
  if (process.env.NODE_ENV !== "test") {
    return <>{children}</>;
  }
}
function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          enableSystem
          defaultTheme="dark"
          attribute="class"
          disableTransitionOnChange
        >
          <Toaster />
          <ClerkProvider>
            <TRPCProvider>{children}</TRPCProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
